services:
  app:
    build: .
    container_name: product_data_pipeline
    volumes:
      - ./images:/app/images
      - ./output:/app/output
      - ./product_data.db:/app/product_data.db
      - ./client_secrets.json:/app/client_secrets.json
      - ./mycreds.txt:/app/mycreds.txt
      - ./.env:/app/.env
    environment:
      - ENV=production
    restart: unless-stopped
