services:
  scraper:
    build: .
    container_name: 1688-scraper
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
      - ./output:/app/output
      - ./client_secrets.json:/app/client_secrets.json
      - ./mycreds.txt:/app/mycreds.txt
    environment:
      - ENV=prod
      - HEADLESS=True
      - CUDA_VISIBLE_DEVICES=
    networks:
      - scraper-network

networks:
  scraper-network:
    driver: bridge